version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket democdlambda --output-template-file outputSamTemplateApi.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplateApi.yaml