version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket bucketfrankfurtdeploypipeline --output-template-file outputSamTemplateLambda.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplateLambda.yaml