AWSTemplateFormatVersion : '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: DemoLambda

Resources:

 myFunctionLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: DeployDemo
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::362697521991:role/PolicyForDeploy'

 AliasForMyApp:
   Type: AWS::Lambda::Alias
   Properties:
     FunctionName:
       Ref: myFunctionLambda
     FunctionVersion: $LATEST
     Name: Prod

 AliasForMyApp2:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName:
        Ref: myFunctionLambda
      FunctionVersion: $LATEST
      Name: dev
