AWSTemplateFormatVersion : '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: DemoLambdaCD

Resources:

  Permission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Principal: apigateway.amazonaws.com
      Action: lambda:InvokeFunction
      FunctionName: arn:aws:lambda:eu-central-1:362697521991:function:DeployLambdaCP:Prod
      SourceArn:  arn:aws:execute-api:eu-central-1:362697521991:3pgpflb87f/*/GET/Prod







