AWSTemplateFormatVersion : '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: DemoLambdaCD

Resources:
# Details about the myDateTimeFunction Lambda function
  myFunctionLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::362697521991:role/PolicyForDeploy'
      Events:
        cdDeploy:
          Type: Api
          Properties:
            Path: /test
            Method: get



  ServerlessRestApiDeployment7536f03888:
    Type: "AWS::ApiGateway::Deployment"
    Properties:
      RestApiId: !Ref ServerlessRestApi
      StageName: Stage2
  ServerlessRestApiProdStage:
    Type: "AWS::ApiGateway::Stage"
    Properties:
      DeploymentId: !Ref ServerlessRestApiDeployment7536f03888
      RestApiId: !Ref ServerlessRestApi
      StageName: "Prod2"

  RestAPIDeployment:
    Type: "AWS::ApiGateway::Deployment"

  RestAPI:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Description: "API to get Car Image"
      Name: "MyAPI"

  ServerlessRestApi:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Body:
        info:
          version: "1.0"

