AWSTemplateFormatVersion : '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: DemoLambdaCD

Resources:
# Details about the myDateTimeFunction Lambda function
  myFunctionLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::362697521991:role/PolicyForDeploy'
      Events:
        cdDeploy:
          Type: Api
          Properties:
            Path: /test
            Method: get

        RestApi:
          Type: AWS::ApiGateway::RestApi
          Properties:
            Body:
              swagger: 2.0
              info:
                version: 0.0.1
                title: test
              basePath: /pete
              schemes:
                - https
              definitions:
                Empty:
                  type: object
            Name: myApi
            Parameters:
              endpointConfigurationTypes: REGIONAL



