AWSTemplateFormatVersion : '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: DemoLambdaCD

Resources:

  MyRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Description: A test API !
      Name: MyRestAPI

  Stack:
    Type: 'AWS::ApiGateway::Resource'
    DependsOn: MyRestApi
    Properties:
      RestApiId: !Ref MyRestApi
      ParentId: !GetAtt
        - MyRestApi
        - RootResourceId
      PathPart: Prod

  Method:
    Type: 'AWS::ApiGateway::Method'
    DependsOn:
      - Stack
      - myFunctionLambda
    Properties:
      HttpMethod: GET
      ResourceId: !Ref Stack
      RestApiId: !Ref MyRestApi
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        Uri: !Sub 'arn:aws:lambda:eu-west-3:362697521991:function:LambdaCDdemo-myFunctionLambda-1K3C4PBH98V1C'

  Stage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      StageName: 'test3'
      RestApiId: !Ref MyRestApi
      DeploymentId: !Ref Deploy

  Deploy:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref MyRestApi
      StageName: 'DummyStage'

  # Details about the myDateTimeFunction Lambda function
  myFunctionLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::362697521991:role/PolicyForDeploy'



