AWSTemplateFormatVersion : '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: DemoLambda

Resources:

  MyRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: A test API !
      Name: MyRestAPIDemo
  Stack:
    Type: AWS::ApiGateway::Resource
    DependsOn: MyRestApi
    Properties:
      RestApiId:
        Ref: MyRestApi
      ParentId:
        Fn::GetAtt:
          - MyRestApi
          - RootResourceId
      PathPart: Prod
  Method:
    Type: AWS::ApiGateway::Method
    DependsOn:
      - Stack
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: Stack
      RestApiId:
        Ref: MyRestApi
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: arn:aws:apigateway:eu-west-3:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-3:362697521991:function:branchlambda-myFunctionLambda-1KU5NR2EHM53B:${stageVariables.lambdaAlias}/invocations
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: Empty
  Deploy:
    Type: AWS::ApiGateway::Deployment
    DependsOn: Method
    Properties:
      RestApiId:
        Ref: MyRestApi
      StageName: Prod
  Stage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: test
      RestApiId:
        Ref: MyRestApi
      DeploymentId:
        Ref: Deploy
      Variables:
        lambdaAlias: Prod3





