AWSTemplateFormatVersion : '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: DemoLambdaCD

Resources:

  MyRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Description: A test API !
      Name: MyRestAPI

  Stack:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref MyRestApi
      ParentId: !GetAtt
        - MyRestApi
        - RootResourceId
      PathPart: test

  Method:
    Type: 'AWS::ApiGateway::Method'
    DependsOn:
      - MyRestApi
      - Stack
    Properties:
      HttpMethod: GET
      ResourceId: !Ref Stack
      RestApiId: !Ref MyRestApi
      AuthorizationType: NONE

  Stage:
    Type: 'AWS::ApiGateway::Stage'
    DependsOn:
      - Method
    Properties:
      StageName: toto
      RestApiId: !Ref MyRestApi
  #Deploy:
    #Type: 'AWS::ApiGateway::Deployment'
    #DependsOn:
      #- Method
      #- Stack
      #- MyRestApi
    #Properties:
      #RestApiId: !Ref MyRestApi
      #StageName: test





  # Details about the myDateTimeFunction Lambda function
  myFunctionLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::362697521991:role/PolicyForDeploy'



