AWSTemplateFormatVersion : '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: DemoLambda

Resources:

 myFunctionLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: DeployLambdaCP
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::362697521991:role/PolicyForDeploy'

 MyRestApiCP2:
   Type: AWS::ApiGateway::RestApi
   Properties:
     Description: A test API !
     Name: MyRestAPIDemo

 Stack:
   Type: AWS::ApiGateway::Resource
   DependsOn: MyRestApiCP2
   Properties:
     RestApiId:
       Ref: MyRestApiCP2
     ParentId:
       Fn::GetAtt:
         - MyRestApiCP2
         - RootResourceId
     PathPart: Prod

 Method:
   Type: AWS::ApiGateway::Method
   DependsOn:
     - Stack
   Properties:
     HttpMethod: GET
     ResourceId:
       Ref: Stack
     RestApiId:
       Ref: MyRestApiCP2
     AuthorizationType: NONE
     Integration:
       Type: AWS_PROXY
       IntegrationHttpMethod: POST
       Uri: !Sub arn:aws:apigateway:eu-west-3:lambda:path/2015-03-31/functions/${myFunctionLambda.Arn}:${stageVariables.lambdaAlias}/invocations
       IntegrationResponses:
         - StatusCode: 200
           ResponseTemplates:
             application/json: Empty
 Deploy:
   Type: AWS::ApiGateway::Deployment
   DependsOn: Method
   Properties:
     RestApiId:
       Ref: MyRestApiCP2
     StageName: Prod
 Stage:
   Type: AWS::ApiGateway::Stage
   Properties:
     StageName: test
     RestApiId:
       Ref: MyRestApiCP2
     DeploymentId:
       Ref: Deploy
     Variables:
       lambdaAlias: Prod
 Stage2:
   Type: AWS::ApiGateway::Stage
   Properties:
     StageName: PETER
     RestApiId:
       Ref: MyRestApiCP2
     DeploymentId:
       Ref: Deploy



