AWSTemplateFormatVersion : '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: DemoLambda

Resources:

  MyRestApiCP:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: A test API !
      Name: MyRestAPIDemo2
  Stack:
    Type: AWS::ApiGateway::Resource
    DependsOn: MyRestApiCP
    Properties:
      RestApiId:
        Ref: MyRestApiCP
      ParentId:
        Fn::GetAtt:
          - MyRestApiCP
          - RootResourceId
      PathPart: Prod
  Method:
    Type: AWS::ApiGateway::Method
    DependsOn:
      - Stack
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: Stack
      RestApiId:
        Ref: MyRestApiCP
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:362697521991:function:DeployLambdaCP:${stageVariables.lambdaAlias}/invocations
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: Empty
  Deploy:
    Type: AWS::ApiGateway::Deployment
    DependsOn: Method
    Properties:
      RestApiId:
        Ref: MyRestApiCP
      StageName: Prod
  Stage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: test2
      RestApiId:
        Ref: MyRestApiCP
      DeploymentId:
        Ref: Deploy
      Variables:
        lambdaAlias: Prod
  Stage2:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: PETER
      RestApiId:
        Ref: MyRestApiCP
      DeploymentId:
        Ref: Deploy
      Variables:
        lambdaAlias: Prod




