AWSTemplateFormatVersion : '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: DemoLambdaCD

Resources:
# Details about the myDateTimeFunction Lambda function
  myFunctionLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::362697521991:role/PolicyForDeploy'
      Events:
        cdDeploy:
          Type: Api
          Properties:
            Path: /test
            Method: get

  RestApi:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Description: "some rest api"
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: RestApi

  SomeResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId:
        Fn::GetAtt:
          - "RestApi"
          - "RootResourceId"
      PathPart: part
      RestApiId:
        Ref: "RestApi"

  SomeSubResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId:
        Ref: "SomeResource"
      PathPart: count
      RestApiId:
        Ref: "RestApi"

  SomeResponseModel:
    Type: "AWS::ApiGateway::Model"
    Properties:
      ContentType: "text/html"
      Description: "Empty text/html response."
      Name: someresponse
      RestApiId:
        !Ref RestApi
      Schema: {}

  PostMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      HttpMethod: POST
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
      MethodResponses:
        - ResponseModels:
            Key: "application/x-www.form-urlencoded"
            Value:
              !Ref SomeResponse
          ResponseParameters:
            - method.response.header.Content-Length: true
            - method.response.header.Content-Type: true
            - method.response.header.Connection: true
          StatusCode: 200
      OperationName: SomeName
      ResourceId:
        !Ref "SomeSubResource"
      RestApiId:
        !Ref "RestApi"



