AWSTemplateFormatVersion : '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: DemoLambdaCD2

Resources:
# Details about the myDateTimeFunction Lambda function

  myFunctionLambda2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function2.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode2
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::362697521991:role/PolicyForDeploy'
      Events:
        cdDeploy2:
          Type: Api
          Properties:
            Path: /deploy
            Method: get

